"""Add France e-invoice fields

Revision ID: 87bb1e79fe8d
Revises: 
Create Date: 2025-12-12 17:19:51.492801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87bb1e79fe8d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('siren', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('invoice_email', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('invoice_phone', sa.String(length=30), nullable=True))

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('siren', sa.String(length=20), nullable=True))

    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fr_document_type', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('fr_transaction_category', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('fr_payment_means', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('fr_payment_terms_text', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_column('fr_payment_terms_text')
        batch_op.drop_column('fr_payment_means')
        batch_op.drop_column('fr_transaction_category')
        batch_op.drop_column('fr_document_type')

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_column('siren')

    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_column('invoice_phone')
        batch_op.drop_column('invoice_email')
        batch_op.drop_column('siren')

    # ### end Alembic commands ###
