"""Add BankAccount model and Company settings fields

Revision ID: 9510ad8d0ce2
Revises: e5e744d71b66
Create Date: 2025-12-14 22:41:54.068746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9510ad8d0ce2'
down_revision = 'e5e744d71b66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bank_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('account_holder', sa.String(length=200), nullable=True),
    sa.Column('bank_name', sa.String(length=200), nullable=True),
    sa.Column('iban', sa.String(length=50), nullable=True),
    sa.Column('bic', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('numbering_mode', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('fiscal_year', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('invoice_prefix', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('starting_invoice_number', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('payment_terms', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('currency', sa.String(length=3), nullable=True))
        batch_op.add_column(sa.Column('einvoice_channel', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('einvoice_format', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('supplier_pdp_name', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('supplier_pdp_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('default_terms', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('default_notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('industry', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('company_addresses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company_addresses', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('industry')
        batch_op.drop_column('default_notes')
        batch_op.drop_column('default_terms')
        batch_op.drop_column('supplier_pdp_id')
        batch_op.drop_column('supplier_pdp_name')
        batch_op.drop_column('einvoice_format')
        batch_op.drop_column('einvoice_channel')
        batch_op.drop_column('currency')
        batch_op.drop_column('payment_terms')
        batch_op.drop_column('starting_invoice_number')
        batch_op.drop_column('invoice_prefix')
        batch_op.drop_column('fiscal_year')
        batch_op.drop_column('numbering_mode')

    op.drop_table('bank_accounts')
    # ### end Alembic commands ###
