"""Add buyer e-invoicing fields to customer

Revision ID: e5e744d71b66
Revises: 87bb1e79fe8d
Create Date: 2025-12-12 19:01:08.054804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5e744d71b66'
down_revision = '87bb1e79fe8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('buyer_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('delivery_channel', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('buyer_pdp_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('buyer_invoice_email', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('po_required', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('buyer_reference', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('default_po_number', sa.String(length=50), nullable=True))
        batch_op.alter_column('siren',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.alter_column('siren',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.drop_column('default_po_number')
        batch_op.drop_column('buyer_reference')
        batch_op.drop_column('po_required')
        batch_op.drop_column('buyer_invoice_email')
        batch_op.drop_column('buyer_pdp_id')
        batch_op.drop_column('delivery_channel')
        batch_op.drop_column('buyer_type')

    # ### end Alembic commands ###
